# Generated by Django 3.2.4 on 2021-12-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='xlSheet',
            new_name='txtReport',
        ),
    ]
